# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cvt < Formula
  desc "Contract Validation Tool - Validate HTTP interactions against OpenAPI specs"
  homepage "https://github.com/sahina/cvt"
  version "0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sahina/cvt/releases/download/v0.2/cvt_0.2_darwin_amd64.tar.gz"
      sha256 "a772396116a60d5f9eaf99fa6e305dc27ea1cf5d1d765552b50cdb1ee0223f92"

      def install
        bin.install "cvt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sahina/cvt/releases/download/v0.2/cvt_0.2_darwin_arm64.tar.gz"
      sha256 "1e8ef200770ef019f0bd8125a3827ad448dbe4e42ad517673d2af243a60ca151"

      def install
        bin.install "cvt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sahina/cvt/releases/download/v0.2/cvt_0.2_linux_amd64.tar.gz"
      sha256 "eef5afc7803e47ba7b3aa439f8804da1b5c9028ed6336d7df029b6575909ce5c"
      def install
        bin.install "cvt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sahina/cvt/releases/download/v0.2/cvt_0.2_linux_arm64.tar.gz"
      sha256 "b9340563e30d53dea841441de024a08ceddf934eea34819091fc161f79930881"
      def install
        bin.install "cvt"
      end
    end
  end

  test do
    system "#{bin}/cvt", "version"
  end
end
