# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cvt < Formula
  desc "Contract Validation Tool - Validate HTTP interactions against OpenAPI specs"
  homepage "https://github.com/sahina/cvt"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sahina/cvt/releases/download/v0.6.1/cvt_0.6.1_darwin_amd64.tar.gz"
      sha256 "a9b801cf60340e60c16c4bb43d1b90ac39f35adf396e7376236037c815b6392d"

      define_method(:install) do
        bin.install "cvt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sahina/cvt/releases/download/v0.6.1/cvt_0.6.1_darwin_arm64.tar.gz"
      sha256 "3fc2067a863917b63f7f3d7b3ac0c07bcc770fe46f551816c670b6646a01ca7b"

      define_method(:install) do
        bin.install "cvt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sahina/cvt/releases/download/v0.6.1/cvt_0.6.1_linux_amd64.tar.gz"
      sha256 "fa4e2e8171b085ea48c3f68f9d7c6d3c3b6338c018cbc4f23945f49645d1af17"
      define_method(:install) do
        bin.install "cvt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sahina/cvt/releases/download/v0.6.1/cvt_0.6.1_linux_arm64.tar.gz"
      sha256 "75f4c46ed35a466b01f35da336e4c70062dd1056ea16f2cbd7a8eb1597a469c9"
      define_method(:install) do
        bin.install "cvt"
      end
    end
  end

  test do
    system "#{bin}/cvt", "version"
  end
end
