# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cvt < Formula
  desc "Contract Validation Tool - Validate HTTP interactions against OpenAPI specs"
  homepage "https://github.com/sahina/cvt"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sahina/cvt/releases/download/v0.6.0/cvt_0.6.0_darwin_amd64.tar.gz"
      sha256 "82882fc92d96239494b6a191778166ce44fe074e671136c69bc82e416c3d7275"

      define_method(:install) do
        bin.install "cvt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sahina/cvt/releases/download/v0.6.0/cvt_0.6.0_darwin_arm64.tar.gz"
      sha256 "36d6a4f0229521920d44e53638c4c7bff9ad9b3dc8e8b81b064caa6e24432164"

      define_method(:install) do
        bin.install "cvt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sahina/cvt/releases/download/v0.6.0/cvt_0.6.0_linux_amd64.tar.gz"
      sha256 "175d1e1764939e9b5eef3518faaaa3a5b34c329a2927f51d1c278326a8b8e704"
      define_method(:install) do
        bin.install "cvt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sahina/cvt/releases/download/v0.6.0/cvt_0.6.0_linux_arm64.tar.gz"
      sha256 "2dd4cbc49c9816b8a1414ad5840032a62b31e37e519ca445d88cc25cfee0e973"
      define_method(:install) do
        bin.install "cvt"
      end
    end
  end

  test do
    system "#{bin}/cvt", "version"
  end
end
