# typed: false
# frozen_string_literal: true

# This file was generated by update-homebrew.sh. DO NOT EDIT.

require_relative "../lib/private_strategy"

class Ironflow < Formula
  desc "Ironflow - Event-driven backend platform"
  homepage "https://github.com/sahina/ironflow"
  license "MIT"
  version "0.11.0"

  on_macos do
    on_intel do
      url "https://github.com/sahina/ironflow/releases/download/v0.11.0/ironflow_0.11.0_darwin_amd64.tar.gz",
          using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e8cfdf3345209b19d0dd00e6ff8aab0b44bf214bb99c817c9e46f30010201b0c"
    end
    on_arm do
      url "https://github.com/sahina/ironflow/releases/download/v0.11.0/ironflow_0.11.0_darwin_arm64.tar.gz",
          using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "543aa61b6c4876cadbd1179df4574150657f82a142f983727719cd6f81aca526"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sahina/ironflow/releases/download/v0.11.0/ironflow_0.11.0_linux_amd64.tar.gz",
          using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a4ed863990519481d276b46aa4cd626fad8ea60a5af97bf33d6bbfd5646ca22c"
    end
    on_arm do
      url "https://github.com/sahina/ironflow/releases/download/v0.11.0/ironflow_0.11.0_linux_arm64.tar.gz",
          using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5ff386c6895c5122bf64d1d7535199da59a698828ea57996552f2a1c64b31287"
    end
  end

  def install
    bin.install "ironflow"
  end

  test do
    system "#{bin}/ironflow", "version"
  end
end
