# typed: false
# frozen_string_literal: true

# This file was generated by update-homebrew.sh. DO NOT EDIT.

require_relative "../lib/private_strategy"

class Ironflow < Formula
  desc "Ironflow - Event-driven backend platform"
  homepage "https://github.com/sahina/ironflow"
  license "MIT"
  version "0.18.0"

  on_macos do
    on_intel do
      url "https://github.com/sahina/ironflow/releases/download/v0.18.0/ironflow_0.18.0_darwin_amd64.tar.gz",
          using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b3eafb624801c23ea61ebc6de017ecbf02bd166550283a456f01cd0a56979fd8"
    end
    on_arm do
      url "https://github.com/sahina/ironflow/releases/download/v0.18.0/ironflow_0.18.0_darwin_arm64.tar.gz",
          using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fb6e1c0628970994c7502578032750a50e926a890d109c9f68ae3229d2cf94a7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sahina/ironflow/releases/download/v0.18.0/ironflow_0.18.0_linux_amd64.tar.gz",
          using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2b27145e92d5e1b59a68a97f30b2ea81af7059e24cd32030db0549d27b36f431"
    end
    on_arm do
      url "https://github.com/sahina/ironflow/releases/download/v0.18.0/ironflow_0.18.0_linux_arm64.tar.gz",
          using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1aaf06f5dfc6de1eb0e960b25a77a626280f691fd5592b7656504a92b2796dc0"
    end
  end

  def install
    bin.install "ironflow"
  end

  test do
    system "#{bin}/ironflow", "version"
  end
end
