# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ironflow < Formula
  desc "Ironflow - Event-driven backend platform"
  homepage "https://ironflow.run"
  version "0.22.5"
  license "LicenseRef-Ironflow-EULA"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sahina/ironflow-releases/releases/download/v0.22.5/ironflow_0.22.5_darwin_amd64.tar.gz"
      sha256 "633a49ed38dd6403cfcbf0287bcb80f4614fe5a98aaef46f0ea1b08e53b12937"

      define_method(:install) do
        bin.install "ironflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sahina/ironflow-releases/releases/download/v0.22.5/ironflow_0.22.5_darwin_arm64.tar.gz"
      sha256 "b9d176b77378e4dcdd55101a877a91bbf2e0b36932c9de9165c2c47bfcb1dec1"

      define_method(:install) do
        bin.install "ironflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sahina/ironflow-releases/releases/download/v0.22.5/ironflow_0.22.5_linux_amd64.tar.gz"
      sha256 "42e3be8f86d2e4d52508052207c5cbd48565bf7b1054a1befa2d6040ea3a4f0e"
      define_method(:install) do
        bin.install "ironflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sahina/ironflow-releases/releases/download/v0.22.5/ironflow_0.22.5_linux_arm64.tar.gz"
      sha256 "b33aaf2f31bcb9936c40ab7e2d1223fe290423403ee223768fb0653e94e33efd"
      define_method(:install) do
        bin.install "ironflow"
      end
    end
  end

  test do
    system "#{bin}/ironflow", "version"
  end
end
